name: f002
description: A new Flutter Application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.5.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+5
  http: ^0.13.4
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_native_splash: ^1.3.1

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  fonts:
      - family: Jua
        fonts:
        - asset: assets/font/Jua-Regular.ttf
          
        

flutter_native_splash:
  color: "#FF5C4B"